Creatly/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from users import views
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.home, name='home'),
    url(r'^contact/', views.contact, name='contact'),
    url(r'^prices/', views.prices, name='prices'),
    url(r'^about/', views.about, name='about'),
    url(r'^service/', views.services, name='services'),
    url(r'^reg/', views.registration, name='reg'),
    url(r'^user_login/', views.user_login, name='user_login'),
    url(r'^example/', views.example, name='example'),
    url(r'^Uwl/', views.UWl, name='User_Wlist'),
    url(r'^users/', include('users.urls')),
    url(r'^Tmps/', views.tmps, name='Template_store'),
    url(r'^logout/', include('users.urls')),

]

users/urls.py
from django.conf.urls import url
from users import views

app_name = 'users'
urlpatterns = [
    url(r'^users/', views.usershome, name='users_home'),
    url(r'^pbuilder/', views.pagebuilder, name='page_builder'),
    url(r'^/', views.user_logout, name='log_out'),

]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django_countries.fields import CountryField


# Create your models here.
class UserProfileInfo(models.Model):
    MEMBER_CHOICES = (('free', 'Free'), ('minimal', 'Minimal'), ('premium', 'Premium'))
    user = models.OneToOneField(User, primary_key=True, on_delete=models.CASCADE)
    profile_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)
    ucountry = CountryField()
    ucity = models.CharField(max_length=256, blank=False)
    ustreetAddress = models.CharField(max_length=256, blank=False)
    umembership = models.CharField(max_length=225, choices=MEMBER_CHOICES)

    def __str__(self):
        return self.user.username


class PaymentMethods(models.Model):
    PAYMENT_CHOICES = [('FAW', 'fawry'), ('VFC', 'vodafone cash'), ('CC', 'Credit card'), ('C', 'Cash')]
    userp = models.ForeignKey(User, on_delete=models.CASCADE)
    pmthid = models.AutoField(primary_key=True)
    paymethod = models.CharField(max_length=200, choices=PAYMENT_CHOICES)


class WebSites(models.Model):
    userw = models.ForeignKey(User, on_delete=models.CASCADE)
    wid = models.AutoField(primary_key=True)
    wname = models.CharField(max_length=255, blank=False)
    wpath = models.CharField(max_length=255)


class WebsiteOptions(models.Model):
    SITEOPT = models.ForeignKey(WebSites, on_delete=models.CASCADE)
    option = models.CharField(max_length=255)


class Pages(models.Model):
    PID = models.AutoField(models.UniqueConstraint, primary_key=True)
    pname = models.CharField(max_length=255)
    ppath = models.CharField(max_length=500)
    SITEPAGE = models.ForeignKey(WebSites, on_delete=models.PROTECT)


class Elements(models.Model):
    eid = models.CharField(models.UniqueConstraint, max_length=100, primary_key=True)
    PPATH = models.ForeignKey(Pages, on_delete=models.PROTECT)
    index = models.IntegerField()


class ElementClasses(models.Model):
    CLASSELEMENT = models.ForeignKey(Elements, on_delete=models.PROTECT)
    classes = models.CharField(max_length=500)


class ElementAttributes(models.Model):
    ATTRIELEMENT = models.ForeignKey(Elements, on_delete=models.PROTECT)
    attributes = models.CharField(max_length=500)

users/forms.py
from django import forms
from django.contrib.auth.models import User

from users.models import UserProfileInfo, PaymentMethods, WebSites
from django.core import validators


class NewUserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password')


class NewUserInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ('profile_site', 'profile_pic', 'ucountry', 'ucity', 'ustreetAddress', 'umembership')


class NewPaymentMethodForm(forms.ModelForm):
    class Meta:
        model = PaymentMethods
        fields = ('paymethod',)


class NewWebsiteForm(forms.ModelForm):
    class Meta:
        model = WebSites
        fields = ('wname',)

users/views.py
from django.shortcuts import render
from users.models import User
# from . import forms
from users.forms import NewUserForm, NewUserInfoForm

from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required


# Create your views here.


def prices(request):
    my_dict = {'insert_me': "Hello I am from views.py"}
    return render(request, 'priceplans.html', context=my_dict)


def contact(request):
    my_dict = {'insert_me': "Hello I am from views.py"}
    return render(request, 'contactus.html', context=my_dict)


def about(request):
    my_dict = {'insert_me': "Hello I am from views.py"}
    return render(request, 'aboutus.html', context=my_dict)


def home(request):
    return render(request, 'home.html')


def services(request):
    my_dict = {'insert_me': "Hello I am from views.py"}
    return render(request, 'services.html', context=my_dict)


def registration(request):
    registered = False
    if request.method == "POST":
        userform = NewUserForm(data=request.POST)
        userinfo = NewUserInfoForm(data=request.POST)

        if userform.is_valid() and userinfo.is_valid():
            user = userform.save()
            user.set_password(user.password)
            user.save()

            profile = userinfo.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(userform.errors, userinfo.errors)

    else:
        userform = NewUserForm()
        userinfo = NewUserInfoForm()

    return render(request, 'registration.html', {'userform': userform, 'userinfo': userinfo, 'registered': registered})


def example(request):
    my_dict = {'insert_me': "Hello I am from views.py"}
    return render(request, 'examples.html', context=my_dict)


@login_required
def UWl(request):
    my_dict = {
        'Add_opt': '<span class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="far fa-ellipsis-v"></i></span><div class="dropdown-menu" aria-labelledby="dropdownMenuButton"><a class="dropdown-item" href="#">Edit</a><a class="dropdown-item" href="#">Up</a><a class="dropdown-item" href="#">Down</a><a class="dropdown-item" href="#">Remove</a></div>'}
    return render(request, 'User_Wlist.html', context=my_dict)


def usershome(request):
    my_dict = {'insert_me': "Hello I am from views.py"}
    return render(request, 'usershome.html', context=my_dict)


def user_login(request):
    if request.method == 'POST':
        # First get the username and password supplied
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Django's built-in authentication function:
        user = authenticate(username=username, password=password)

        # If we have a user
        if user:
            # Check it the account is active
            if user.is_active:
                # Log the user in.
                login(request, user)
                # Send the user back to some page.
                # In this case their homepage.
                return HttpResponseRedirect(reverse('home'))
            else:
                # If account is not active:
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username, password))
            return HttpResponse("Invalid login details supplied.")

    else:
        # Nothing has been provided for username or password.
        return render(request, 'userlogin.html', {})


@login_required
def user_logout(request):
    # Log out the user.
    logout(request)
    # Return to homepage.
    return HttpResponseRedirect(reverse('home'))


@login_required
def pagebuilder(request):
    return render(request, 'pagebuilder.html', {})


def tmps(request):
    my_dict = {'insert_me': "Hello I am from views.py"}
    return render(request, 'Template_store.html', context=my_dict)

templates/User_Wlist.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}

 <div class="row">
        <div class="col-8" >
            <div class="border">
            <h2>Created Websites</h2>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Website Name</th>
      <th scope="col">VIEWS</th>
      <th scope="col">SALES</th>
      <th scope="col">TOTAL</th>
      <th scope="col">...</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">Web1</th>
      <td>455556</td>
      <td>123584</td>
      <td>0.25</td>
        <td>{{Add_opt|safe|escape}}</td>



    </tr>
    <tr>
      <th scope="row">Web2</th>
      <td>4556548</td>
      <td>454645</td>
      <td>445588</td>
        <td>{{Add_opt|safe|escape}}</td>
    </tr>
    <tr>
      <th scope="row">Web3</th>
      <td>444788</td>
      <td>455456</td>
      <td>4455</td>
        <td>{{Add_opt|safe|escape}}</td>
    </tr>
  </tbody>
</table>
            </div></div>
 <div class="col-4">
    <button type="button" class="btn btn-primary btn-lg">Add new Website</button>

 </div>
 </div>

{% endblock %}

templates/aboutus.html
{% extends 'base.html' %}
{% block title %}
    About Us
{% endblock %}


{% load staticfiles %}
{% block content %}
    <div class="aboutUsContainer">
        <img class="aboutUsContainer-img" src="{% static 'images/AboutUsBG.png' %}" alt="">
        <h2 class="aboutUsContainer-h">About Us</h2>
        <p class="aboutUsContainer-p">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
            incididunt
            ut ero labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco poriti
            laboris nisi
            ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in uienply voluptate velit esse
            cillum dolore
            eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat norin proident, sunt in culpa qui officia
            deserunt mollit
            anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
            incididunt ut ero labore et dolore
            magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco poriti laboris nisi ut aliquip ex
            ea
            commodo consequat. Duis aute irure dolor in reprehenderit in uienply voluptate velit esse cillum dolore eu
            fugiat
            nulla pariatur. Excepteur sint occaecat cupidatat norin proident, sunt in culpa qui officia deserunt mollit
            anim
            id est laborum.</p>
    </div>
    <div class="ab-container">
        <div class="row">
            <div class="col-sm-4"></div>
            <div class="col-sm-4"></div>
            <div class="col-sm-4">
                <div class="circle-e rounded-circle" style=""><h3 class="circle-txt">GOAL</h3></div>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut ero
                    labore
                    et dolore.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt
                    ut ero labore et dolore.
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4"></div>
            <div class="col-sm-4 text-center">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut ero
                    labore
                    et dolore.
                </p>
                <div class="circle-o rounded-circle"><h3 class="circle-txt-o">VISION</h3></div>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt
                    ut
                    ero labore et dolore.
                </p>
            </div>
            <div class="col-sm-4"></div>
        </div>
        <div class="row">
            <div class="col-sm-4 text-center"><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
                eiusmod tempor
                incididunt ut ero labore
                et dolore.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut
                ero labore et dolore.</p>
                <div class="circle-e rounded-circle"><h3 class="circle-txt">MISSION</h3></div>
            </div>
            <div class="col-sm-4"></div>
            <div class="col-sm-4"></div>
        </div>
    </div>

{% endblock %}

templates/contactus.html
{% extends 'base.html' %}
{% block title %}
    Contact Us
{% endblock %}

{% load staticfiles %}
{% block content %}
    <!-- write html here -->





{% endblock %}

templates/examples.html
{% extends 'base.html' %}
{% block title %}
    Examples
{% endblock %}

{% load staticfiles %}
{% block content %}
    <!-- write html here -->





{% endblock %}

templates/pagebuilder.html
{% extends 'base.html' %}
{% block title %}
Pages builder
{% endblock %}

{% load staticfiles %}
{% block content %}
<!-- write html here -->

<div class="row no-gutters">
    <div class="col-lg-12">

    </div>
</div>

<div class="row no-gutters">
    <div class="col-lg-2 compon">

        <div class="row no-gutters">
            <div class=" dragitms">
                <div class="banner"></div>
                <p>banner</p></div>
            <div class="dragitms">
                <div class="covers"></div>
                <p>cover</p></div>
            <div class=" dragitms">
                <div class="image-text"></div>
                <p>Image-Text</p></div>
            <div class=" dragitms">
                <div class="text-image"></div>
                <p>Text-Image</p></div>


            <div class=" dragitms">
                <div class="titles"></div>
                <p>title</p></div>
            <div class=" dragitms">
                <div class="text-block"></div>
                <p>Text block</p></div>


            <div class=" dragitms">
                <div class="pic"></div>
                <p>Picture</p></div>
            <div class=" dragitms">
                <div class="slider"></div>
                <p>Carousel</p></div>

            <div class=" dragitms">
                <div class="features"></div>
                <p>Features</p></div>
            <div class=" dragitms">
                <div class="cols"></div>
                <p>Columns</p></div>


            <div class=" dragitms">
                <div class="pageheader"></div>
                <p>Page Header</p></div>
            <div class=" dragitms">
                <div class="nuamberssy"></div>
                <p>Numbers</p></div>


            <div class=" dragitms">
                <div class="steps"></div>
                <p>Steps</p></div>
            <div class=" dragitms">
                <div class="tprofiles"></div>
                <p>Team Profiles</p></div>


            <div class=" dragitms">
                <div class="imagesrow"></div>
                <p>Images Row</p></div>
            <div class=" dragitms">

            </div>
        </div>


    </div>
    <div class="col-lg-10 cnt"></div>
</div>

{% endblock %}

templates/priceplans.html
{% extends 'base.html' %}
{% block title %}
    Price plans
{% endblock %}

{% load staticfiles %}
{% block content %}






{% endblock %}

templates/registration.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Registration
{% endblock %}

{% load staticfiles %}
{% block content %}
<!-- write html here -->
{% if registered %}
<h1>thank you for registering</h1>
{% else %}

<form enctype="multipart/form-data" method="post">

    <label for="id_first_name">First name:</label><input type="text" name="first_name" maxlength="30"
                                                         id="id_first_name">
    <label for="id_last_name">Last name:</label><input type="text" name="last_name" maxlength="150" id="id_last_name">
    <label for="id_username">Username:</label><input type="text" name="username" maxlength="150" required=""
                                                     id="id_username"><br><span class="helptext cc_cursor">Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</span>
    <label for="id_email">Email address:</label><input type="email" name="email" maxlength="254" id="id_email">
    <label for="id_password">Password:</label><input type="password" name="password" required="" id="id_password">
    <label for="id_profile_site">Profile site:</label><input type="url" name="profile_site" maxlength="200"
                                                             id="id_profile_site">
    <label for="id_profile_pic">Profile pic:</label><input type="file" name="profile_pic" accept="image/*"
                                                           id="id_profile_pic">
    <label for="id_ucountry">Ucountry:</label><select name="ucountry" required="" id="id_ucountry">
    <option value="" selected="">---------</option>

    <option value="AF">Afghanistan</option>

    <option value="AX">Åland Islands</option>

    <option value="AL">Albania</option>

    <option value="DZ">Algeria</option>

    <option value="AS">American Samoa</option>

    <option value="AD">Andorra</option>

    <option value="AO">Angola</option>

    <option value="AI">Anguilla</option>

    <option value="AQ">Antarctica</option>

    <option value="AG">Antigua and Barbuda</option>

    <option value="AR">Argentina</option>

    <option value="AM">Armenia</option>

    <option value="AW">Aruba</option>

    <option value="AU">Australia</option>

    <option value="AT">Austria</option>

    <option value="AZ">Azerbaijan</option>

    <option value="BS">Bahamas</option>

    <option value="BH">Bahrain</option>

    <option value="BD">Bangladesh</option>

    <option value="BB">Barbados</option>

    <option value="BY">Belarus</option>

    <option value="BE">Belgium</option>

    <option value="BZ">Belize</option>

    <option value="BJ">Benin</option>

    <option value="BM">Bermuda</option>

    <option value="BT">Bhutan</option>

    <option value="BO">Bolivia</option>

    <option value="BQ">Bonaire, Sint Eustatius and Saba</option>

    <option value="BA">Bosnia and Herzegovina</option>

    <option value="BW">Botswana</option>

    <option value="BV">Bouvet Island</option>

    <option value="BR">Brazil</option>

    <option value="IO">British Indian Ocean Territory</option>

    <option value="BN">Brunei</option>

    <option value="BG">Bulgaria</option>

    <option value="BF">Burkina Faso</option>

    <option value="BI">Burundi</option>

    <option value="CV">Cabo Verde</option>

    <option value="KH">Cambodia</option>

    <option value="CM">Cameroon</option>

    <option value="CA">Canada</option>

    <option value="KY">Cayman Islands</option>

    <option value="CF">Central African Republic</option>

    <option value="TD">Chad</option>

    <option value="CL">Chile</option>

    <option value="CN">China</option>

    <option value="CX">Christmas Island</option>

    <option value="CC">Cocos (Keeling) Islands</option>

    <option value="CO">Colombia</option>

    <option value="KM">Comoros</option>

    <option value="CG">Congo</option>

    <option value="CD">Congo (the Democratic Republic of the)</option>

    <option value="CK">Cook Islands</option>

    <option value="CR">Costa Rica</option>

    <option value="CI">Côte d'Ivoire</option>

    <option value="HR">Croatia</option>

    <option value="CU">Cuba</option>

    <option value="CW">Curaçao</option>

    <option value="CY">Cyprus</option>

    <option value="CZ">Czechia</option>

    <option value="DK">Denmark</option>

    <option value="DJ">Djibouti</option>

    <option value="DM">Dominica</option>

    <option value="DO">Dominican Republic</option>

    <option value="EC">Ecuador</option>

    <option value="EG">Egypt</option>

    <option value="SV">El Salvador</option>

    <option value="GQ">Equatorial Guinea</option>

    <option value="ER">Eritrea</option>

    <option value="EE">Estonia</option>

    <option value="SZ">Eswatini</option>

    <option value="ET">Ethiopia</option>

    <option value="FK">Falkland Islands [Malvinas]</option>

    <option value="FO">Faroe Islands</option>

    <option value="FJ">Fiji</option>

    <option value="FI">Finland</option>

    <option value="FR">France</option>

    <option value="GF">French Guiana</option>

    <option value="PF">French Polynesia</option>

    <option value="TF">French Southern Territories</option>

    <option value="GA">Gabon</option>

    <option value="GM">Gambia</option>

    <option value="GE">Georgia</option>

    <option value="DE">Germany</option>

    <option value="GH">Ghana</option>

    <option value="GI">Gibraltar</option>

    <option value="GR">Greece</option>

    <option value="GL">Greenland</option>

    <option value="GD">Grenada</option>

    <option value="GP">Guadeloupe</option>

    <option value="GU">Guam</option>

    <option value="GT">Guatemala</option>

    <option value="GG">Guernsey</option>

    <option value="GN">Guinea</option>

    <option value="GW">Guinea-Bissau</option>

    <option value="GY">Guyana</option>

    <option value="HT">Haiti</option>

    <option value="HM">Heard Island and McDonald Islands</option>

    <option value="VA">Holy See</option>

    <option value="HN">Honduras</option>

    <option value="HK">Hong Kong</option>

    <option value="HU">Hungary</option>

    <option value="IS">Iceland</option>

    <option value="IN">India</option>

    <option value="ID">Indonesia</option>

    <option value="IR">Iran</option>

    <option value="IQ">Iraq</option>

    <option value="IE">Ireland</option>

    <option value="IM">Isle of Man</option>

    <option value="IL">Israel</option>

    <option value="IT">Italy</option>

    <option value="JM">Jamaica</option>

    <option value="JP">Japan</option>

    <option value="JE">Jersey</option>

    <option value="JO">Jordan</option>

    <option value="KZ">Kazakhstan</option>

    <option value="KE">Kenya</option>

    <option value="KI">Kiribati</option>

    <option value="KW">Kuwait</option>

    <option value="KG">Kyrgyzstan</option>

    <option value="LA">Laos</option>

    <option value="LV">Latvia</option>

    <option value="LB">Lebanon</option>

    <option value="LS">Lesotho</option>

    <option value="LR">Liberia</option>

    <option value="LY">Libya</option>

    <option value="LI">Liechtenstein</option>

    <option value="LT">Lithuania</option>

    <option value="LU">Luxembourg</option>

    <option value="MO">Macao</option>

    <option value="MG">Madagascar</option>

    <option value="MW">Malawi</option>

    <option value="MY">Malaysia</option>

    <option value="MV">Maldives</option>

    <option value="ML">Mali</option>

    <option value="MT">Malta</option>

    <option value="MH">Marshall Islands</option>

    <option value="MQ">Martinique</option>

    <option value="MR">Mauritania</option>

    <option value="MU">Mauritius</option>

    <option value="YT">Mayotte</option>

    <option value="MX">Mexico</option>

    <option value="FM">Micronesia (Federated States of)</option>

    <option value="MD">Moldova</option>

    <option value="MC">Monaco</option>

    <option value="MN">Mongolia</option>

    <option value="ME">Montenegro</option>

    <option value="MS">Montserrat</option>

    <option value="MA">Morocco</option>

    <option value="MZ">Mozambique</option>

    <option value="MM">Myanmar</option>

    <option value="NA">Namibia</option>

    <option value="NR">Nauru</option>

    <option value="NP">Nepal</option>

    <option value="NL">Netherlands</option>

    <option value="NC">New Caledonia</option>

    <option value="NZ">New Zealand</option>

    <option value="NI">Nicaragua</option>

    <option value="NE">Niger</option>

    <option value="NG">Nigeria</option>

    <option value="NU">Niue</option>

    <option value="NF">Norfolk Island</option>

    <option value="KP">North Korea</option>

    <option value="MK">North Macedonia</option>

    <option value="MP">Northern Mariana Islands</option>

    <option value="NO">Norway</option>

    <option value="OM">Oman</option>

    <option value="PK">Pakistan</option>

    <option value="PW">Palau</option>

    <option value="PS">Palestine, State of</option>

    <option value="PA">Panama</option>

    <option value="PG">Papua New Guinea</option>

    <option value="PY">Paraguay</option>

    <option value="PE">Peru</option>

    <option value="PH">Philippines</option>

    <option value="PN">Pitcairn</option>

    <option value="PL">Poland</option>

    <option value="PT">Portugal</option>

    <option value="PR">Puerto Rico</option>

    <option value="QA">Qatar</option>

    <option value="RE">Réunion</option>

    <option value="RO">Romania</option>

    <option value="RU">Russia</option>

    <option value="RW">Rwanda</option>

    <option value="BL">Saint Barthélemy</option>

    <option value="SH">Saint Helena, Ascension and Tristan da Cunha</option>

    <option value="KN">Saint Kitts and Nevis</option>

    <option value="LC">Saint Lucia</option>

    <option value="MF">Saint Martin (French part)</option>

    <option value="PM">Saint Pierre and Miquelon</option>

    <option value="VC">Saint Vincent and the Grenadines</option>

    <option value="WS">Samoa</option>

    <option value="SM">San Marino</option>

    <option value="ST">Sao Tome and Principe</option>

    <option value="SA">Saudi Arabia</option>

    <option value="SN">Senegal</option>

    <option value="RS">Serbia</option>

    <option value="SC">Seychelles</option>

    <option value="SL">Sierra Leone</option>

    <option value="SG">Singapore</option>

    <option value="SX">Sint Maarten (Dutch part)</option>

    <option value="SK">Slovakia</option>

    <option value="SI">Slovenia</option>

    <option value="SB">Solomon Islands</option>

    <option value="SO">Somalia</option>

    <option value="ZA">South Africa</option>

    <option value="GS">South Georgia and the South Sandwich Islands</option>

    <option value="KR">South Korea</option>

    <option value="SS">South Sudan</option>

    <option value="ES">Spain</option>

    <option value="LK">Sri Lanka</option>

    <option value="SD">Sudan</option>

    <option value="SR">Suriname</option>

    <option value="SJ">Svalbard and Jan Mayen</option>

    <option value="SE">Sweden</option>

    <option value="CH">Switzerland</option>

    <option value="SY">Syria</option>

    <option value="TW">Taiwan</option>

    <option value="TJ">Tajikistan</option>

    <option value="TZ">Tanzania</option>

    <option value="TH">Thailand</option>

    <option value="TL">Timor-Leste</option>

    <option value="TG">Togo</option>

    <option value="TK">Tokelau</option>

    <option value="TO">Tonga</option>

    <option value="TT">Trinidad and Tobago</option>

    <option value="TN">Tunisia</option>

    <option value="TR">Turkey</option>

    <option value="TM">Turkmenistan</option>

    <option value="TC">Turks and Caicos Islands</option>

    <option value="TV">Tuvalu</option>

    <option value="UG">Uganda</option>

    <option value="UA">Ukraine</option>

    <option value="AE">United Arab Emirates</option>

    <option value="GB">United Kingdom</option>

    <option value="UM">United States Minor Outlying Islands</option>

    <option value="US">United States of America</option>

    <option value="UY">Uruguay</option>

    <option value="UZ">Uzbekistan</option>

    <option value="VU">Vanuatu</option>

    <option value="VE">Venezuela</option>

    <option value="VN">Vietnam</option>

    <option value="VG">Virgin Islands (British)</option>

    <option value="VI">Virgin Islands (U.S.)</option>

    <option value="WF">Wallis and Futuna</option>

    <option value="EH">Western Sahara</option>

    <option value="YE">Yemen</option>

    <option value="ZM">Zambia</option>

    <option value="ZW">Zimbabwe</option>

</select>
    <label for="id_ucity">Ucity:</label><input type="text" name="ucity" maxlength="256" required="" id="id_ucity">
    <label for="id_ustreetAddress">UstreetAddress:</label><input type="text" name="ustreetAddress" maxlength="256"
                                                                 required="" id="id_ustreetAddress">
    <label for="id_umembership">Umembership:</label><select name="umembership" required="" id="id_umembership">
    <option value="" selected="">---------</option>

    <option value="free">Free</option>

    <option value="minimal">Minimal</option>

    <option value="premium">Premium</option>

</select>
    <input type="text">
    {% csrf_token %}
    <input type="submit" class="btn btn-primary" value="Submit">
</form>

{% endif %}


{% endblock %}

templates/services.html
{% extends 'base.html' %}
{% block title %}
    Services
{% endblock %}

{% load staticfiles %}
{% block content %}
    <!-- write html here -->





{% endblock %}